### PR TITLE
[mplayer-svn] unified build.sh for macOS and Cygwin

### PR DESCRIPTION
**Pull request by gubatron**

### CODE REVIEW

**Comment by aldenml** [comment]
interesting...don't you need the `cygwin.dll`? how big the executable is?

**Comment by gubatron** [comment]
so this morning when I tried the player on a fresh machine I came up to this realization.

Not only I need `cygwin.dll 3.5 MB` I also need:
`cygcrypto-1.1.dll 3.5 MB` 😂, `cygssl-1.1.dll 506 KB`, `cygpng16-16.dll 189 KB`, `cygjpeg-8.dll 429 KB` and `cygz.dll 85 KB`  

So I'm going to build on ubuntu with mingw toolset, the way it was.

(It was so comfy building with cygwin though, I tried mingw on windows and had all sorts of compiler issues and no easy way to install more packages like on cygwin)

At least I went to bed happy last night :)

**Comment by gubatron** [comment]
however, I was just reading there might be a way to pass "-mno-cygwin" and perhaps I'll need to cross-compile, which might bring another set of hairy issues, so debating now between trying a little more on cygwin or starting over in ubuntu, whatever the case, each test is at least 15mins waiting for the build to fail/pass and then test

**Comment by gubatron** [comment]
`-mno-cygwin` flag has been dead for a long time.

So it seems the path is to make sure the cygwin compilers are uninstalled and that I keep the mingw gcc x86_64 toolchain

**Pull request merged**
